# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 52c6ec1db4fa9318656fa3a2f369b6a514d707c1656de0d371f59aa6821d742f19a6665f25d6e3bb1f5f236f62535aca2e5198211dd93ea8009ed75d4e707076

test:
  secret_key_base: 69bfafdf9be1a413ffbc144ff5f408d7f66fb4d9f1291cabc3b029e38c7996f1992693b2d2351c9543b869002bd2b117a4a9060a3beb535a91149558ba27ebd8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
